server:
  port: 8080

spring:

  application:
    name: beveragestockcontrol-app

  datasource:
    url: jdbc:mysql://localhost:3306/beverage_stock_control
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/beverage_stock_control
    user: root
    password: root
    baseline-on-migrate: true
    database-type: mysql
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui-custom.html"
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
  writer-with-order-by-keys: false